CREATE TABLE [DMAPPS].[BRRW_REL_LKUP] (
    [BRRW_REL_CD]   NUMERIC (2)   NULL,
    [BRRW_REL_DESC] NVARCHAR (50) NULL,
    [BRRW_REL_KEY]  NUMERIC (38)  NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [BRRW_REL_LKUP_CD_KEY]
    ON [DMAPPS].[BRRW_REL_LKUP]([BRRW_REL_CD] ASC, [BRRW_REL_KEY] ASC) WHERE ([BRRW_REL_CD] IS NOT NULL AND [BRRW_REL_KEY] IS NOT NULL);

