CREATE TABLE [DMAPPS].[BRRW_LKUP] (
    [COMM_NO]       CHAR (7)     NULL,
    [CCAN]          CHAR (10)    NULL,
    [BRRW_LKUP_KEY] NUMERIC (38) NOT NULL,
    [MSTR_LKUP_KEY] NUMERIC (38) NULL
);


GO
CREATE NONCLUSTERED INDEX [BRRW_LKUP_CCAN]
    ON [DMAPPS].[BRRW_LKUP]([CCAN] ASC);


GO
CREATE NONCLUSTERED INDEX [BRRW_LKUP_CCAN_COMM]
    ON [DMAPPS].[BRRW_LKUP]([COMM_NO] ASC, [CCAN] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [BRRW_LKUP_CCAN_COMM_KEY]
    ON [DMAPPS].[BRRW_LKUP]([COMM_NO] ASC, [CCAN] ASC, [BRRW_LKUP_KEY] ASC, [MSTR_LKUP_KEY] ASC) WHERE ([COMM_NO] IS NOT NULL AND [CCAN] IS NOT NULL AND [MSTR_LKUP_KEY] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [BRRW_LKUP_CCAN_KEY]
    ON [DMAPPS].[BRRW_LKUP]([CCAN] ASC, [BRRW_LKUP_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [BRRW_LKUP_CCAN_MSTR]
    ON [DMAPPS].[BRRW_LKUP]([CCAN] ASC, [MSTR_LKUP_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [BRRW_LKUP_KEY]
    ON [DMAPPS].[BRRW_LKUP]([BRRW_LKUP_KEY] ASC);


GO
CREATE NONCLUSTERED INDEX [BRRW_LKUP_KEYS]
    ON [DMAPPS].[BRRW_LKUP]([BRRW_LKUP_KEY] ASC, [MSTR_LKUP_KEY] ASC);

