CREATE TABLE [DMAPPS].[BUYR_DIM] (
    [BUYR_KEY]       NUMERIC (38)    NOT NULL,
    [BUYR_NAME]      CHAR (50)       NULL,
    [BUYR_NO]        CHAR (2)        NULL,
    [BUYR_TITL]      CHAR (40)       NULL,
    [BUYR_INITLS]    CHAR (3)        NULL,
    [BUYR_MGR_IND]   NUMERIC (1)     NULL,
    [BUYR_INACT_IND] NUMERIC (1)     NULL,
    [BUYR_DEPT]      CHAR (5)        NULL,
    [BUYR_CA_PASS]   NUMERIC (11, 2) NULL,
    [BUYR_CA_FAIL]   NUMERIC (11, 2) NULL,
    [BUYR_FEND_ACS]  CHAR (45)       NULL,
    [BUYR_LOAD_TS]   NUMERIC (14)    NULL,
    [BUYR_UPDT_TS]   NUMERIC (14)    NULL,
    [BUYR_UPLD_IND]  NUMERIC (1)     NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [BUYR_DIM_KEY]
    ON [DMAPPS].[BUYR_DIM]([BUYR_KEY] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [BUYR_DIM_NO_INI_KEY]
    ON [DMAPPS].[BUYR_DIM]([BUYR_NO] ASC, [BUYR_TITL] ASC, [BUYR_KEY] ASC) WHERE ([BUYR_NO] IS NOT NULL AND [BUYR_TITL] IS NOT NULL);

