CREATE TABLE [DMAPPS].[CAE_APPLICATIONAGREEMENT_T] (
    [APPLICATIONSOURCESYSTEM] NVARCHAR (10) NOT NULL,
    [APPLICATIONNUMBER]       NVARCHAR (10) NOT NULL,
    [AGREEMENTSOURCESYSTEM]   NVARCHAR (10) NULL,
    [AGREEMENTNUMBER]         NVARCHAR (20) NULL,
    CONSTRAINT [SYS_C0012785] PRIMARY KEY CLUSTERED ([APPLICATIONSOURCESYSTEM] ASC, [APPLICATIONNUMBER] ASC)
);

