CREATE TABLE [DMAPPS].[CAE_APPLICATIONPARTY_T] (
    [APPLICATIONSOURCESYSTEM] NVARCHAR (10) NOT NULL,
    [APPLICATIONNUMBER]       NVARCHAR (10) NOT NULL,
    [PARTYSOURCESYSTEM]       NVARCHAR (10) NULL,
    [PARTYNUMBER]             NVARCHAR (10) NULL,
    [APPLPARTYROLETYPECD]     NVARCHAR (10) NULL,
    CONSTRAINT [SYS_C0012787] PRIMARY KEY CLUSTERED ([APPLICATIONSOURCESYSTEM] ASC, [APPLICATIONNUMBER] ASC)
);

