CREATE TABLE [DMAPPS].[CAE_APPLICATIONCLASS_T] (
    [APPLICATIONSOURCESYSTEM] NVARCHAR (10) NOT NULL,
    [APPLICATIONNUMBER]       NVARCHAR (10) NOT NULL,
    [APPLCLASSTYPECODE]       NVARCHAR (20) NOT NULL,
    [APPLCLASSCODE]           NVARCHAR (10) NULL,
    CONSTRAINT [SYS_C0012761] PRIMARY KEY CLUSTERED ([APPLICATIONSOURCESYSTEM] ASC, [APPLICATIONNUMBER] ASC, [APPLCLASSTYPECODE] ASC)
);

