CREATE TABLE [DMAPPS].[CAE_APPLICATIONFEATURE_T] (
    [APPLICATIONSOURCESYSTEM] NVARCHAR (10) NULL,
    [APPLICATIONNUMBER]       NVARCHAR (10) NOT NULL,
    [FEATURENAME]             NVARCHAR (40) NOT NULL,
    [VALUEALPHANUMERIC]       NVARCHAR (20) NULL,
    [VALUENUMERIC]            NVARCHAR (10) NULL,
    [VALUEDATETIME]           NVARCHAR (20) NULL,
    CONSTRAINT [SYS_C0012786] PRIMARY KEY CLUSTERED ([APPLICATIONNUMBER] ASC, [FEATURENAME] ASC)
);

