CREATE TABLE [DMAPPS].[CART_BKUP_BASEL] (
    [COMM_NO]    NVARCHAR (10)   NULL,
    [WW_ID]      NVARCHAR (10)   NULL,
    [RUN_DATE]   NVARCHAR (15)   NULL,
    [FINALPDPCT] NUMERIC (13, 2) NULL,
    [FINALPD_BP] NUMERIC (13, 2) NULL,
    [FINALRGRAD] NVARCHAR (10)   NULL
);

