CREATE TABLE [DMAPPS].[CART_BKUP_ASSETRESIDUAL] (
    [COMM_NO]   NVARCHAR (10)   NOT NULL,
    [RESID_PCT] NUMERIC (12, 2) NULL,
    [RESID_AMT] NUMERIC (12, 2) NULL,
    [HOURLTERM] NUMERIC (12, 2) NULL,
    [HOURDLVDT] NUMERIC (12, 2) NULL
);

