CREATE TABLE [DMAPPS].[CARTMOSAIC] (
    [COMM_NO]      NVARCHAR (7)  NULL,
    [CARTMOSIACID] NVARCHAR (20) NULL,
    [ID]           NVARCHAR (50) NULL,
    [DATE_]        NVARCHAR (16) NULL,
    [TM_]          NVARCHAR (10) NULL
);

