CREATE TABLE [DMAPPS].[CBDATA] (
    [COMM_NO]  NVARCHAR (10) NULL,
    [WEB_DATA] NVARCHAR (50) NULL
);


GO
CREATE NONCLUSTERED INDEX [CBDATA_IDX]
    ON [DMAPPS].[CBDATA]([COMM_NO] ASC);


GO
ALTER INDEX [CBDATA_IDX]
    ON [DMAPPS].[CBDATA] DISABLE;

