CREATE TABLE [DMAPPS].[CICA_FEED](
	[APP_ID] [nvarchar](20) NULL,
	[APP_ENTRY_DATE] [nvarchar](28) NULL,
	[ENTITY_ID] [nvarchar](20) NULL,
	[AMOUNT] [numeric](15, 3) NULL,
	[CUSTOMER_EMAIL] [nvarchar](50) NULL,
	[EQUIPMENT_USE] [nvarchar](20) NULL,
	[HBE_CODE] [nvarchar](10) NULL,
	[IS_APPROVED] [nvarchar](10) NULL,
	[IS_DECISION_RECEIVED] [nvarchar](10) NULL,
	[IS_APP_SUBMITTED] [nvarchar](10) NULL,
	[LINE_OF_BUSINESS] [nvarchar](10) NULL,
	[TRANSACTION_ID] [nvarchar](50) NULL,
	[CUSTOMER_ZIPCODE] [nvarchar](20) NULL,
	[IS_CUSTOMER_EMAIL_SENT] [nvarchar](10) NULL,
	[CONFIRM_CUSTOMER_EMAIL] [nvarchar](100) NULL,
	[SSN] [nvarchar](20) NULL,
	[CONFIRM_SSN] [nvarchar](15) NULL,
	[FIRST_NAME] [nvarchar](50) NULL,
	[LAST_NAME] [nvarchar](50) NULL,
	[ADDRESS_1] [nvarchar](100) NULL,
	[ADDRESS_2] [nvarchar](50) NULL,
	[CITY] [nvarchar](50) NULL,
	[STATE] [nvarchar](10) NULL,
	[PHONE] [nvarchar](15) NULL,
	[DOB] [nvarchar](15) NULL,
	[TERMS_AND_CONDITIONS] [nvarchar](15) NULL,
	[THIRD_PARTY_AGREEMENT] [nvarchar](10) NULL,
	[DEALER_CODE] [nvarchar](10) NULL,
	[DEALER_NAME] [nvarchar](100) NULL,
	[DEALER_EMAIL] [nvarchar](100) NULL,
	[CPQ_ID] [nvarchar](20) NULL,
	[RECORD_ID] [nvarchar](20) NULL,
	[PREFERRED_CONTACT] [nvarchar](60) NULL,
	[SYSTEM_DECISION] [nvarchar](5) NULL,
	[FICO_SCORE] [nvarchar](5) NULL,
	[ML_SCORE] [nvarchar](5) NULL,
	[CURRENCY] [nvarchar](5) NULL,
	[MIDDLE_NAME] [nvarchar](25) NULL,
	[PROVINCE] [nvarchar](5) NULL,
	[POSTAL_CODE] [nvarchar](10) NULL,
	[SIN] [nvarchar](15) NULL,
	[CONFIRM_SIN] [nvarchar](15) NULL,
	[COUNTRY] [nvarchar](5) NULL,
	[PREFERRED_LANGUAGE] [nvarchar](10) NULL,
	[VENDOR_CODE] [nvarchar](50) NULL,
	[VENDOR_NAME] [nvarchar](50) NULL,
	[VENDOR_EMAIL] [nvarchar](50) NULL,
	[LVL] [nvarchar](25) NULL,
	[PRIMARY_PARTNER_TYPE] [nvarchar](20) NULL,
	[PRIMARY_PARTNER_ID] [nvarchar](10) NULL,
	[PRIMARY_PARTNER_NAME] [nvarchar](100) NULL,
	[PRIMARY_PARTNER_EMAIL] [nvarchar](50) NULL,
	[HAS_ICV_SEARCH_ERROR] [nvarchar](5) NULL,
	[OVERALL_EXPERIENCE] [numeric](38, 10) NULL,
	[EASE_OF_USE] [numeric](38, 10) NULL,
	[TIME_TO_COMPLETE] [numeric](38, 10) NULL,
	[SURVEY_COMMENTS] [nvarchar](1000) NULL
);

