CREATE TABLE [DMAPPS].[CO_BRRW_DM] (
    [REL_TO_BRRW] NUMERIC (38) NULL,
    [CO_BRRW_KEY] NUMERIC (38) NOT NULL,
    [BRRW_KEY]    NUMERIC (38) NOT NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CO_BRRW_DM_ALL]
    ON [DMAPPS].[CO_BRRW_DM]([CO_BRRW_KEY] ASC, [BRRW_KEY] ASC);


GO
ALTER INDEX [CO_BRRW_DM_ALL]
    ON [DMAPPS].[CO_BRRW_DM] DISABLE;

